# Generated by Django 5.1.7 on 2025-03-19 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_remove_products_image_productsimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='availablity',
            new_name='availability',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='owner.products')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductsImages',
        ),
    ]
