# Generated by Django 5.1.7 on 2025-03-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_rename_availablity_products_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('availability', models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], default='In Stock', max_length=50)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='products/images/')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
