# Generated by Django 5.1.7 on 2025-03-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='owner/files/covers'),
        ),
    ]
