# Generated by Django 5.1.7 on 2025-03-20 11:12

import owner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_alter_product_image1_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image6',
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=owner.models.filepath),
        ),
    ]
