# Generated by Django 5.1.7 on 2025-03-20 14:26

import django.db.models.deletion
import owner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0011_rename_image1_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=owner.models.filepath)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='owner.product')),
            ],
        ),
    ]
