# Generated by Django 5.1.7 on 2025-03-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0012_remove_product_image_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='Product',
            new_name='product',
        ),
    ]
