# Generated by Django 5.1.7 on 2025-03-20 15:02

import owner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0013_rename_product_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=owner.models.filepath),
        ),
    ]
